# Secrets.toml
SMTP_EMAIL="stmtk13044032@gmail.com"
SMTP_PASSWORD="hzrg9nlg"
DOMAIN="http://localhost:8080"

# You can create a Secrets.dev.toml to use secrets in a development environment - in this case, you can set domain to "127.0.0.1" and copy the other two variables as required.